version: 2
jobs:
  build1:
    working_directory: ~/letters-social
    docker:
      - image: circleci/node:12.16.1
        environment:
          NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
  build2:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - run: 
         name: hello
         command: echo "hello" 
# workflows:
#   version: 2
#   build_and_deploy:
#     jobs:
#      - build1
#      - deploy:
#        requires:
#          - build1