version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
        environment:
          NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
  deploy:
    machine:
      - enabled: true
    steps:
      - run: 
          name: Deploy over SSH
          command: |
            sshpass -p uSfUFtN2C894eKyrnSH ssh -p 55462 root@15.165.115.215 "echo hello"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build