version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
        environment:
          NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
  deploy:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - run: 
         name: hello
         command: echo "hello" 
workflows:
  version: 2
  build_and_deploy:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - deploy:
          type: approval
          requires:
            - build